### ISSUE TITLE
plots

### ISSUE THREAD

**Issue by bkrishnamachari** [ANRGUSC/lacounty_covid19_data#2]
On the plots: 
1) would be good to have the x axis start from 1 and be labeled "Days since March 16, 2020"
2) would be good to have also plots that show the y-axis in log scale (will need it soon enough :( )

**Comment by mehrdadkiam** [comment]
I made the x axis starts from 1 and labeled as "Days since March 16, 2020".
Also made the y axis logarithmic with same name extended with "_log".
